title: first post
date: 2020-12-26
theme: minima
title: Dannys life
author: Daniel Everheart
email: danther98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal glance into my life

# social links
twitter_username: danther98
github_username:  danther98

show_excerpts: true # set to false to remove excerpts on the homepage
